# Generated by scripts/generate.py from openapi.json. Do not edit.
"""The API's resources, as the SDK returns them."""

from __future__ import annotations

from datetime import datetime
from typing import Any, TypeAlias

from pydantic import BaseModel as _BaseModel
from pydantic import ConfigDict as _ConfigDict
from pydantic import Field as _Field


class NoheadModel(_BaseModel):
    """Base of every model: fields the SDK does not know yet are kept."""

    model_config = _ConfigDict(extra="allow", populate_by_name=True)


class Health(NoheadModel):
    status: str
    version: str
    """Nohead API version."""
    time: Timestamp


class ListMeta(NoheadModel):
    """Cursor pagination metadata returned with every list."""

    next_cursor: str | None
    """Opaque cursor for the next page, or null on the last page."""
    has_more: bool


class Organization(NoheadModel):
    id: str
    object: str
    name: str
    slug: str
    plan: str
    role: str | None
    """The current user's role in the organization."""
    permissions: list[Permission]
    """What the current user's role allows in the organization (empty without a membership).
    Clients use it to show only the actions that will succeed; the API enforces it either
    way.
    """
    grantable_scopes: list[ApiKeyScope]
    """API key scopes the current user may put on new keys: those whose permissions their role
    holds.
    """
    deleted: bool
    """Scheduled for deletion (see `DELETE /v1/organizations/{id}`)."""
    purge_after: NullableTimestamp
    """When a scheduled deletion becomes permanent; null otherwise."""
    created_at: Timestamp
    updated_at: Timestamp


class MembershipUser(NoheadModel):
    id: str
    email: str
    name: str | None


class Membership(NoheadModel):
    id: str
    object: str
    organization_id: str
    user: MembershipUser
    role: Role
    created_at: Timestamp
    updated_at: Timestamp


class MembershipUpdate(NoheadModel):
    role: Role


class MembershipList(NoheadModel):
    data: list[Membership]
    meta: ListMeta


class InvitationOrganization(NoheadModel):
    id: str
    name: str
    slug: str


class InvitationInvitedBy(NoheadModel):
    id: str
    name: str


class InvitationEmailDelivery(NoheadModel):
    status: str
    at: Timestamp


class Invitation(NoheadModel):
    id: str
    object: str
    organization: InvitationOrganization
    email: str
    role: Role
    status: str
    invited_by: InvitationInvitedBy
    email_delivery: InvitationEmailDelivery | None
    """What became of the invitation email, or null while it has not been sent (or when sending
    is off). `sent`: accepted for delivery. `not_sent`: no email went out, because the
    address had bounced or been marked as spam before, or had already received several
    invitation emails that day. `bounced`: the email could not be delivered; check the
    address. `complained`: the invitee marked it as spam. Either way the invitation still
    works when the invitee signs in with the address.
    """
    expires_at: Timestamp
    responded_at: NullableTimestamp
    created_at: Timestamp


class InvitationCreate(NoheadModel):
    email: str
    role: Role


class InvitationList(NoheadModel):
    data: list[Invitation]
    meta: ListMeta


class OrganizationCreate(NoheadModel):
    name: str
    slug: str


class MeUpdate(NoheadModel):
    name: str | None
    """Shown to the members of your organizations; `null` removes it."""


class OrganizationUpdate(NoheadModel):
    name: str | None = None
    slug: str | None = None


class OrganizationList(NoheadModel):
    data: list[Organization]
    meta: ListMeta


class Project(NoheadModel):
    id: str
    object: str
    organization_id: str
    name: str
    slug: str
    settings: dict[str, Any]
    deleted: bool
    """Scheduled for deletion (see `DELETE /v1/projects/{id}`)."""
    purge_after: NullableTimestamp
    """When a scheduled deletion becomes permanent; null otherwise."""
    created_at: Timestamp
    updated_at: Timestamp


class ProjectCreate(NoheadModel):
    organization_id: str
    name: str
    slug: str
    settings: dict[str, Any] | None = None


class ProjectUpdate(NoheadModel):
    name: str | None = None
    slug: str | None = None
    settings: dict[str, Any] | None = None


class ProjectList(NoheadModel):
    data: list[Project]
    meta: ListMeta


class RecordFilterValueObject(NoheadModel):
    eq: str | None = None
    ne: str | None = None
    gt: str | None = None
    gte: str | None = None
    lt: str | None = None
    lte: str | None = None
    in_: str | None = _Field(None, alias="in")
    """Comma-separated; `\\,` is a comma inside a value."""
    exists: str | None = None


class FieldAliases(NoheadModel):
    api_key: str
    expires_at: Timestamp


class Field(NoheadModel):
    id: str
    """Stable field ID. Never changes, even when the field is renamed."""
    object: str
    collection_id: str
    name: str
    """Display name. Safe to change."""
    api_key: str
    """Key used in record data. Part of the API contract."""
    type: FieldType
    required: bool
    multiple: bool
    """A list of distinct values (a repeated value is refused with `duplicate_value`, an empty
    string with `blank_value`). Not available for boolean, long_text, rich_text and json
    fields.
    """
    position: int
    configuration: dict[str, Any]
    """Type-specific options, e.g. `max_length`, `options`, `target_collection_id`,
    `accepted_types` (asset fields: MIME types or `type/*` wildcards that newly written
    values must have; any file when absent), `include_time` and `time_zone` (date fields,
    below), plus the options for searches with API keys: `searchable` (the search words
    match the field; default true for text, long_text, rich_text and enum), `filterable` and
    `sortable` (default false). Date fields hold a calendar date, `YYYY-MM-DD`, with no time
    and no time zone: returned exactly as written, so it never shows as the day before or
    after. With `include_time: true` they hold a moment: ISO 8601 with an offset, stored in
    UTC and returned in UTC, or with the offset of `time_zone` (an IANA name such as
    `Europe/Copenhagen`, daylight saving included) when the field has one. Input may use any
    offset. Changing `time_zone` never rewrites values; turning `include_time` on or off
    does, through a field migration.
    """
    deleted: bool
    aliases: list[FieldAliases]
    """Old API keys of a renamed field that still work until `expires_at`: record data also
    carries the value under them, and writes, filters, sorts and `expand` accept them.
    Responses about the collection then have `Deprecation` and `Sunset` headers.
    """
    created_at: Timestamp
    updated_at: Timestamp


class RecordCount(NoheadModel):
    object: str
    collection_id: str
    count: int


class FieldCreate(NoheadModel):
    name: str
    api_key: str
    type: FieldType
    required: bool | None = None
    multiple: bool | None = None
    """A list of distinct values (a repeated value is refused with `duplicate_value`, an empty
    string with `blank_value`). Not available for boolean, long_text, rich_text and json
    fields.
    """
    position: int | None = None
    configuration: dict[str, Any] | None = None


class FieldUpdate(NoheadModel):
    name: str | None = None
    api_key: str | None = None
    type: FieldType | None = None
    required: bool | None = None
    multiple: bool | None = None
    """A list of distinct values (a repeated value is refused with `duplicate_value`, an empty
    string with `blank_value`). Not available for boolean, long_text, rich_text and json
    fields.
    """
    position: int | None = None
    configuration: dict[str, Any] | None = None


class FieldList(NoheadModel):
    data: list[Field]
    meta: ListMeta


class Collection(NoheadModel):
    id: str
    object: str
    project_id: str
    name: str
    slug: str
    description: str | None
    schema_version: int
    deleted: bool
    search_enabled: bool
    """Whether API keys can search the collection (`GET
    /v1/collections/{collection_id}/search`). Every collection is indexed; members can
    search it in the web app either way.
    """
    fields: list[Field]
    """Active fields in position order."""
    created_at: Timestamp
    updated_at: Timestamp


class CollectionCreate(NoheadModel):
    search_enabled: bool | None = None
    name: str
    slug: str
    description: str | None = None
    fields: list[FieldCreate] | None = None


class CollectionUpdate(NoheadModel):
    search_enabled: bool | None = None
    name: str | None = None
    slug: str | None = None
    description: str | None = None


class CollectionList(NoheadModel):
    data: list[Collection]
    meta: ListMeta


class SchemaDefinitionFields(NoheadModel):
    id: str
    name: str
    api_key: str
    type: FieldType
    required: bool
    multiple: bool
    position: int
    configuration: dict[str, Any]
    deleted: bool


class SchemaDefinition(NoheadModel):
    """The complete collection definition at one schema version."""

    id: str
    name: str
    slug: str
    description: str | None
    deleted: bool
    search_enabled: bool | None = None
    fields: list[SchemaDefinitionFields]


class Schema(NoheadModel):
    object: str
    collection_id: str
    version: int
    definition: SchemaDefinition


class Actor(NoheadModel):
    type: str
    id: str | None
    """The user (`usr_...`) or API key (`key_...`), or null for system changes."""
    name: str | None
    """Resolved when read, never stored: a user's current name (or email), "Deleted user" once
    they deleted their account, an API key's name, or "System".
    """


class SchemaChangeProperties(NoheadModel):
    id: str
    object: str
    collection_id: str
    from_version: int
    to_version: int
    operation: str
    payload: dict[str, Any]
    """Operation details, e.g. `changes` and `breaking` for updates."""
    actor: Actor
    via: ChangeVia
    note: str | None
    request_id: str | None
    status: str
    created_at: Timestamp


class SchemaChangeDetail(SchemaChangeProperties):
    before: SchemaDefinition | None
    after: SchemaDefinition


class SchemaChangeList(NoheadModel):
    data: list[SchemaChange]
    meta: ListMeta


class FieldDefinition(NoheadModel):
    type: FieldType
    configuration: dict[str, Any]
    multiple: bool
    """A list of distinct values (a repeated value is refused with `duplicate_value`, an empty
    string with `blank_value`). Not available for boolean, long_text, rich_text and json
    fields.
    """
    required: bool


class FieldMigrationRequest(NoheadModel):
    """The parts of the definition to change; omitted parts stay as they are."""

    type: FieldType | None = None
    configuration: dict[str, Any] | None = None
    """The complete new configuration. When the type changes and this is omitted, only
    `description` carries over.
    """
    multiple: bool | None = None
    """A list of distinct values (a repeated value is refused with `duplicate_value`, an empty
    string with `blank_value`). Not available for boolean, long_text, rich_text and json
    fields.
    """
    required: bool | None = None
    backfill: Any = None
    """Value for active records that have no value, validated like a record value of the new
    definition; an empty string is refused with `blank_value`.
    """
    on_invalid: str | None = None
    """`clear` removes values that cannot be converted (or backfills them); `fail` refuses the
    migration.
    """
    time_zone: str | None = None
    """When a date field's `include_time` is turned off: the IANA time zone (e.g.
    `Europe/Copenhagen`) whose day each moment falls on. Default: the field's `time_zone`,
    else UTC. Refused for any other change.
    """


class FieldMigrationCounts(NoheadModel):
    """Records by outcome, including soft-deleted records (which are converted but never
    backfilled).
    """

    total: int
    unchanged: int
    converted: int
    backfilled: int
    cleared: int
    invalid: int


class FieldMigrationPreviewSamplesError(NoheadModel):
    code: str
    message: str


class FieldMigrationPreviewSamples(NoheadModel):
    record_id: str
    deleted: bool
    outcome: str
    before: Any
    """The stored value before the migration, or null."""
    after: Any
    """The value after the migration, or null when cleared or invalid."""
    error: FieldMigrationPreviewSamplesError | None


class FieldMigrationPreview(NoheadModel):
    object: str
    field_id: str
    from_: FieldDefinition = _Field(alias="from")
    to: FieldDefinition
    conversion: str
    """`safe`: every value converts unchanged in meaning. `convertible`: every value converts,
    the representation changes. `conditional`: some values may not convert.
    """
    records: FieldMigrationCounts
    samples: list[FieldMigrationPreviewSamples]
    """Up to 10 affected records, invalid ones first."""


class FieldMigrationBackfill(NoheadModel):
    value: Any


class FieldMigrationFailure(NoheadModel):
    message: str


class FieldMigration(NoheadModel):
    id: str
    object: str
    collection_id: str
    field_id: str
    status: str
    from_: FieldDefinition = _Field(alias="from")
    to: FieldDefinition
    backfill: FieldMigrationBackfill | None
    """`{"value": ...}` when missing values are filled in, otherwise null."""
    on_invalid: str
    time_zone: str | None
    """The time zone dates were read in when `include_time` was turned off, if one was given."""
    records: FieldMigrationCounts
    failure: FieldMigrationFailure | None
    """Why the migration failed; null otherwise. A failed migration changed nothing."""
    schema_change_id: str | None
    """The `migrate_field` schema change, once complete."""
    cancel_requested: bool
    actor: Actor
    via: ChangeVia
    note: str | None
    request_id: str | None
    created_at: Timestamp
    started_at: NullableTimestamp
    completed_at: NullableTimestamp


class FieldMigrationList(NoheadModel):
    data: list[FieldMigration]
    meta: ListMeta


class RecordSchedule(NoheadModel):
    """When the record publishes or unpublishes on its own (within a minute of the time), set
    with `PUT /v1/records/{record_id}/schedule`. A time is cleared once it has run.
    `last_error` explains the last scheduled change that could not be made, until a new
    schedule is set.
    """

    publish_at: NullableTimestamp
    unpublish_at: NullableTimestamp
    last_error: str | None


class RecordScheduleUpdate(NoheadModel):
    """A time in the future, or null for none. Omitted keys keep their value."""

    publish_at: NullableTimestamp | None = None
    unpublish_at: NullableTimestamp | None = None


class Record(NoheadModel):
    id: str
    object: str
    collection_id: str
    collection: str
    """The collection slug."""
    status: str
    published_at: NullableTimestamp
    schedule: RecordSchedule
    revision: int
    """Current revision number; also returned as the ETag."""
    schema_version: int
    history_pruned_through: int | None
    """Revisions up to this number (except revision 1) were removed by the plan's history
    retention.
    """
    deleted: bool
    data: RecordData
    expanded: dict[str, Record | Asset | list[Record | Asset] | None] | None = None
    """Only with `expand`: what each requested relation, asset or rich text field points at,
    keyed by field API key: records for relation fields, assets for asset fields. A single
    value is the object, or null when it no longer exists; a multiple value is a list of
    those that still exist. For a rich text field, the list of assets its images show, in
    document order, leaving out those that no longer exist. Expanded records are not
    expanded further.
    """
    created_at: Timestamp
    updated_at: Timestamp


class RecordWrite(NoheadModel):
    data: RecordData


class RecordList(NoheadModel):
    data: list[Record]
    meta: ListMeta


class Change(NoheadModel):
    """One change between two states. Field changes carry `field` (current API key) and the
    stable `field_id`; attribute changes (`status`, `published_at`, `deleted`) carry
    `attribute`.
    """

    field: str | None = None
    field_id: str | None = None
    field_deleted: bool | None = None
    attribute: str | None = None
    kind: str
    before: Any = None
    after: Any = None


class RecordRevisionProperties(NoheadModel):
    id: str
    object: str
    record_id: str
    revision: int
    operation: str
    actor: Actor
    via: Via
    note: str | None
    schema_version: int
    reverted_to_revision: int | None
    changed_fields: list[str]
    """API keys of changed fields, and changed attributes."""
    redacted_fields: list[str]
    """API keys of fields whose values in this revision were redacted (`POST
    /v1/records/{id}/redact`); those values read `{"$redacted": true}`.
    """
    created_at: Timestamp


class Redaction(NoheadModel):
    object: str
    record_id: str
    field: str
    """The field's API key."""
    field_id: str
    revisions: list[int]
    """Revision numbers whose snapshot or changes were (or would be) rewritten."""
    values: int
    """How many distinct past values were (or would be) redacted."""
    dry_run: bool


class RecordRevisionDetail(RecordRevisionProperties):
    status: str
    published_at: NullableTimestamp
    data: RecordData
    changes: list[Change]


class RecordRevisionList(NoheadModel):
    data: list[RecordRevision]
    meta: ListMeta


class RecordDiff(NoheadModel):
    object: str
    record_id: str
    from_: int = _Field(alias="from")
    to: int
    changes: list[Change]


class RevertPreview(NoheadModel):
    object: str
    record_id: str
    to_revision: int
    data: RecordData
    changes: list[Change]


class FeatureFlags(NoheadModel):
    object: str
    organization_id: str | None
    project_id: str | None
    flags: dict[str, bool]
    """Flag name to enabled, for every registered flag the caller may see."""


class AccountDeletion(NoheadModel):
    object: str
    user_id: str
    """The deleted user, as history still refers to it."""
    deleted_at: datetime


class PrincipalUser(NoheadModel):
    id: str
    email: str
    name: str | None
    staff: bool
    """Nohead staff (internal tooling access)."""


class PrincipalApiKey(NoheadModel):
    id: str
    name: str
    scopes: list[ApiKeyScope]
    published_only: PublishedOnly
    project_id: str
    expires_at: NullableTimestamp


class Principal(NoheadModel):
    object: str
    type: str
    user: PrincipalUser | None
    api_key: PrincipalApiKey | None


class SearchResultsMeta(NoheadModel):
    next_cursor: str | None
    has_more: bool
    total_estimate: int
    """Approximate number of matches."""


class SearchResults(NoheadModel):
    data: list[Record]
    meta: SearchResultsMeta


class SearchIndex(NoheadModel):
    object: str
    collection_id: str
    enabled: bool
    """The collection's `search_enabled`; the index is kept up to date either way."""
    status: str
    """`building` until first built; `stale` from the change that queues a rebuild until it has
    run; `failed` if the last rebuild failed (it is retried).
    """
    documents: int
    last_built_at: NullableTimestamp
    rebuild_requested_at: NullableTimestamp


class WebhookProperties(NoheadModel):
    id: str
    object: str
    project_id: str
    url: str
    description: str | None
    event_types: list[str]
    """The subscribed event types, or `["*"]` for all."""
    enabled: bool
    deleted: bool
    created_at: Timestamp
    updated_at: Timestamp


class WebhookWithSecret(WebhookProperties):
    secret: str
    """The signing secret (`whsec_...`). Keep it private."""


class BulkRecordsRequest(NoheadModel):
    action: str
    record_ids: list[str]
    data: dict[str, Any] | None = None
    """For `update`, the fields to set on every record (null clears one)."""


class BulkRecordsResultResults(NoheadModel):
    id: str
    status: str
    changed: bool
    """False when the record was already in that state (no revision)."""
    record: Record


class BulkRecordsResult(NoheadModel):
    object: str
    action: str
    succeeded: int
    failed: int
    results: list[BulkRecordsResultResults]


class Billing(NoheadModel):
    object: str
    organization_id: str
    enabled: bool
    """Whether checkout and the billing portal are available."""
    plan: str
    subscription: BillingSubscription | None
    """The Stripe subscription behind a paid plan, or null."""
    plans: list[BillingPlan]


class BillingSubscription(NoheadModel):
    status: str
    """Stripe's subscription status; `past_due` keeps the plan while Stripe retries payment."""
    interval: str | None
    current_period_end: datetime | None
    cancel_at_period_end: bool


class BillingPlanPrices(NoheadModel):
    interval: str
    amount: float
    """In whole currency units, before tax."""
    currency: str


class BillingPlan(NoheadModel):
    key: str
    name: str
    limits: dict[str, int | None]
    """The plan's limits; null values are unlimited."""
    prices: list[BillingPlanPrices]
    """Empty for free and custom plans."""


class BillingCheckout(NoheadModel):
    plan: str
    interval: str | None = None
    return_path: str | None = None
    """A path in the web app to come back to, e.g. `/organizations/org_.../usage`."""


class BillingPortal(NoheadModel):
    return_path: str | None = None


class BillingSession(NoheadModel):
    object: str
    url: str


class AccessReviewApiKeys(NoheadModel):
    api_key: ApiKey
    reason: str
    """`creator_left`: its creator is no longer a member. `exceeds_creator_role`: it holds a
    scope the creator's current role cannot grant.
    """


class AccessReviewInvitations(NoheadModel):
    invitation: Invitation
    reason: str
    """`inviter_left`: whoever sent it is no longer a member. `inviter_cannot_invite`: their
    current role cannot invite to this role.
    """


class AccessReview(NoheadModel):
    object: str
    organization_id: str
    api_keys: list[AccessReviewApiKeys]
    invitations: list[AccessReviewInvitations]


class UsagePlan(NoheadModel):
    key: str
    name: str


class UsagePeriod(NoheadModel):
    """The current period; `end` is exclusive."""

    start: str
    end: str


class Usage(NoheadModel):
    object: str
    organization_id: str
    plan: UsagePlan
    period: UsagePeriod
    """The current period; `end` is exclusive."""
    metrics: list[UsageMetric]
    retention: UsageRetention


class UsageRetention(NoheadModel):
    """How long the plan keeps record revisions (beyond each record's first and latest 10) and
    audit events, in days; null keeps everything.
    """

    revision_days: int | None
    audit_days: int | None
    grace: UsageRetentionGrace | None
    """After a downgrade, all history is kept for 30 days; history past the plan's retention is
    removed after `ends_at`. Null otherwise.
    """


class UsageRetentionGrace(NoheadModel):
    ends_at: datetime
    revision_days: int | None
    """Days of revisions kept until `ends_at`; null keeps everything (as a downgrade's grace
    does).
    """
    audit_days: int | None
    """Days of audit events kept until `ends_at`; null keeps everything (as a downgrade's grace
    does).
    """


class UsageMetricDaily(NoheadModel):
    date: str
    value: int


class UsageMetric(NoheadModel):
    metric: str
    kind: str
    usage: int
    limit: int | None
    """The plan's limit, or null when unlimited or not limited."""
    enforcement: str
    """`hard` refuses changes over the limit (402), `soft` warns, `off` only meters."""
    daily: list[UsageMetricDaily] | None = None
    """Counters only, one entry per day with usage."""


class AuditEventProject(NoheadModel):
    id: str
    name: str


class AuditEventResource(NoheadModel):
    type: str
    id: str
    """The resource's public ID (or key, for feature flags)."""


class AuditEvent(NoheadModel):
    id: str
    object: str
    organization_id: str
    project: AuditEventProject | None
    """The project the event belongs to, or null for organization-level events."""
    action: str
    """`<resource>.<verb>`, e.g. `record.published`, `field.updated`, `api_key.created`,
    `member.role_changed`.
    """
    resource: AuditEventResource
    actor: Actor
    via: str | None
    """The client the change came through, when known."""
    metadata: dict[str, Any]
    """Small, action-specific references, e.g. `revision_id` and `collection_id` for record
    events, `schema_change_id` for schema events, `changed` attribute names for updates.
    Never content.
    """
    request_id: str | None
    created_at: datetime


class AuditEventList(NoheadModel):
    data: list[AuditEvent]
    meta: ListMeta


class WebhookList(NoheadModel):
    data: list[Webhook]
    meta: ListMeta


class WebhookCreate(NoheadModel):
    url: str
    """An https URL on the public internet."""
    description: str | None = None
    event_types: list[WebhookEventType | str]
    enabled: bool | None = None


class WebhookUpdate(NoheadModel):
    url: str | None = None
    description: str | None = None
    event_types: list[WebhookEventType | str] | None = None
    enabled: bool | None = None


class WebhookDeliveryPropertiesEvent(NoheadModel):
    id: str
    """The event ID, sent as `webhook-id`; the same on every attempt."""
    type: str
    created_at: Timestamp


class WebhookDeliveryProperties(NoheadModel):
    id: str
    object: str
    webhook_id: str
    event: WebhookDeliveryPropertiesEvent
    status: str
    """`pending` until an attempt gets a 2xx response; `failed` after 8 attempts over about a
    day.
    """
    attempts_count: int
    last_status_code: int | None
    last_error: str | None
    last_attempt_at: NullableTimestamp
    next_attempt_at: NullableTimestamp
    succeeded_at: NullableTimestamp
    created_at: Timestamp


class WebhookDeliveryDetailAttempts(NoheadModel):
    number: int
    status_code: int | None
    error: str | None
    duration_ms: int
    response_body: str | None
    """The first 2 KB of the response."""
    created_at: Timestamp


class WebhookDeliveryDetail(WebhookDeliveryProperties):
    payload: WebhookEventPayload
    attempts: list[WebhookDeliveryDetailAttempts]


class WebhookDeliveryList(NoheadModel):
    data: list[WebhookDelivery]
    meta: ListMeta


class WebhookEventPayload(NoheadModel):
    """The JSON body of every webhook request."""

    id: str
    object: str
    type: str
    """One of the event types, or `webhook.test`."""
    created_at: Timestamp
    project_id: str
    data: dict[str, Any]
    """`record.*`: `record` (the record after the change), `revision` and `revision_id`.
    `asset.*`: `asset`. `schema.changed`: `collection` and `schema_change`. `webhook.test`:
    `webhook`.
    """


class Asset(NoheadModel):
    id: str
    object: str
    project_id: str
    filename: str
    """The original filename, any Unicode."""
    content_type: str
    byte_size: int
    width: int | None
    """Pixel width, for images."""
    height: int | None
    status: str
    """`pending` until the upload is completed; only `ready` assets can be used in records."""
    deleted: bool
    preview_url: str | None
    """A signed URL of a small rendition (fits in 640×640, WebP), for ready images, deleted
    ones included until they are purged; null otherwise.
    """
    uploaded_at: NullableTimestamp
    created_at: Timestamp
    updated_at: Timestamp


class AssetList(NoheadModel):
    data: list[Asset]
    meta: ListMeta


class ImageUrl(NoheadModel):
    object: str
    asset_id: str
    url: str
    width: int | None
    height: int | None
    fit: str
    format: str
    quality: int | None


class AssetUsageUses(NoheadModel):
    record: Record
    fields: list[str]
    """API keys of the record's fields that use the asset."""


class AssetUsage(NoheadModel):
    object: str
    asset_id: str
    records: int
    """Undeleted records that use the asset."""
    published: int
    """Of those, the published ones (what sites show)."""
    uses: list[AssetUsageUses]
    """The most recently updated records that use the asset."""


class DownloadUrl(NoheadModel):
    object: str
    asset_id: str
    url: str
    expires_at: Timestamp


class AssetUploadCreate(NoheadModel):
    filename: str
    content_type: str
    byte_size: int
    """Exact size of the file in bytes (at most 100 MB by default)."""


class AssetUploadUpload(NoheadModel):
    method: str
    url: str
    headers: dict[str, str]
    """Headers to send with the upload."""
    expires_at: Timestamp


class AssetUpload(NoheadModel):
    object: str
    asset: Asset
    upload: AssetUploadUpload


class ApiKeyProperties(NoheadModel):
    id: str
    object: str
    project_id: str
    name: str
    scopes: list[ApiKeyScope]
    published_only: PublishedOnly
    token_hint: str
    """The non-secret start of the token, to recognize it."""
    expires_at: NullableTimestamp
    last_used_at: NullableTimestamp
    revoked_at: NullableTimestamp
    created_by: str | None
    created_at: Timestamp


class ApiKeyWithToken(ApiKeyProperties):
    token: str
    """The secret token. Returned only once, at creation."""


class ApiKeyCreate(NoheadModel):
    name: str
    scopes: list[ApiKeyScope]
    published_only: PublishedOnly | None = None
    expires_at: NullableTimestamp | None = None


class ApiKeyList(NoheadModel):
    data: list[ApiKey]
    meta: ListMeta


class ErrorDetail(NoheadModel):
    field: str | None = None
    """API key of the offending field or parameter, when applicable."""
    code: str
    """Machine-readable error code, e.g. `required`."""
    message: str
    usage: int | None = None
    """Current usage, for `plan_limit` details."""
    limit: int | None = None
    """The plan's limit, for `plan_limit` details."""
    current_revision: int | None = None
    """The resource's current revision, for `revision_mismatch` details."""


class ErrorError(NoheadModel):
    type: ErrorType
    message: str
    request_id: RequestId
    details: list[ErrorDetail] | None = None


class Error(NoheadModel):
    error: ErrorError


RequestId: TypeAlias = str
Timestamp: TypeAlias = datetime
NullableTimestamp: TypeAlias = datetime | None
Role: TypeAlias = str
Permission: TypeAlias = str
RecordFilterValue: TypeAlias = str | RecordFilterValueObject
FieldType: TypeAlias = str
SchemaChange: TypeAlias = SchemaChangeProperties
Via: TypeAlias = str
ChangeVia: TypeAlias = str
RecordData: TypeAlias = dict[str, Any]
RecordRevision: TypeAlias = RecordRevisionProperties
WebhookEventType: TypeAlias = str
Webhook: TypeAlias = WebhookProperties
WebhookDelivery: TypeAlias = WebhookDeliveryProperties
ApiKeyScope: TypeAlias = str
ApiKey: TypeAlias = ApiKeyProperties
PublishedOnly: TypeAlias = bool
ErrorType: TypeAlias = str

for _model in list(globals().values()):
    if isinstance(_model, type) and issubclass(_model, NoheadModel):
        _model.model_rebuild()
