# Generated by scripts/generate.py from openapi.json. Do not edit.
"""The request bodies of the API, for type checkers."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal, NotRequired, TypeAlias, TypedDict


class AssetUploadCreate(TypedDict):
    filename: str
    content_type: str
    byte_size: int
    """Exact size of the file in bytes (at most 100 MB by default)."""


class BulkRecordsRequest(TypedDict):
    action: Literal["publish", "unpublish", "delete", "restore", "update"]
    record_ids: list[str]
    data: NotRequired[dict[str, Any]]
    """For `update`, the fields to set on every record (null clears one)."""


class CollectionCreate(TypedDict):
    search_enabled: NotRequired[bool]
    name: str
    slug: str
    description: NotRequired[str | None]
    fields: NotRequired[list[FieldCreate]]


class CollectionUpdate(TypedDict):
    search_enabled: NotRequired[bool]
    name: NotRequired[str]
    slug: NotRequired[str]
    description: NotRequired[str | None]


class FieldCreate(TypedDict):
    name: str
    api_key: str
    type: FieldType
    required: NotRequired[bool]
    """Every record must have a value. Not available for boolean fields (a boolean is true or
    false; no value reads as false).
    """
    multiple: NotRequired[bool]
    """A list of distinct values (a repeated value is refused with `duplicate_value`, an empty
    string with `blank_value`). Not available for boolean, long_text, rich_text and json
    fields.
    """
    configuration: NotRequired[dict[str, Any]]


class FieldMigrationRequest(TypedDict):
    """The parts of the definition to change; omitted parts stay as they are."""

    type: NotRequired[FieldType]
    configuration: NotRequired[dict[str, Any]]
    """The complete new configuration. When the type changes and this is omitted, only
    `description`, `searchable`, `filterable` and `sortable` carry over.
    """
    multiple: NotRequired[bool]
    """A list of distinct values (a repeated value is refused with `duplicate_value`, an empty
    string with `blank_value`). Not available for boolean, long_text, rich_text and json
    fields.
    """
    required: NotRequired[bool]
    backfill: NotRequired[Any]
    """Value for active records that have no value, validated like a record value of the new
    definition; an empty string is refused with `blank_value`.
    """
    on_invalid: NotRequired[Literal["fail", "clear"]]
    """`clear` removes values that cannot be converted (or backfills them); `fail` refuses the
    migration.
    """
    time_zone: NotRequired[str]
    """When a date field's `include_time` is turned off: the IANA time zone (e.g.
    `Europe/Copenhagen`) whose day each moment falls on. Default: the field's `time_zone`,
    else UTC. Refused for any other change.
    """


class FieldUpdate(TypedDict):
    name: NotRequired[str]
    api_key: NotRequired[str]
    type: NotRequired[FieldType]
    required: NotRequired[bool]
    """Every record must have a value. Not available for boolean fields (a boolean is true or
    false; no value reads as false).
    """
    multiple: NotRequired[bool]
    """A list of distinct values (a repeated value is refused with `duplicate_value`, an empty
    string with `blank_value`). Not available for boolean, long_text, rich_text and json
    fields.
    """
    configuration: NotRequired[dict[str, Any]]


class RecordScheduleUpdate(TypedDict):
    """A time in the future, or null for none. Omitted keys keep their value."""

    publish_at: NotRequired[NullableTimestamp]
    unpublish_at: NotRequired[NullableTimestamp]


class RecordWrite(TypedDict):
    data: RecordData


class WebhookCreate(TypedDict):
    url: str
    """An https URL on the public internet."""
    description: NotRequired[str | None]
    event_types: list[WebhookEventType | Literal["*"]]
    enabled: NotRequired[bool]


class WebhookUpdate(TypedDict):
    url: NotRequired[str]
    description: NotRequired[str | None]
    event_types: NotRequired[list[WebhookEventType | Literal["*"]]]
    enabled: NotRequired[bool]


FieldType: TypeAlias = Literal[
    "text",
    "long_text",
    "rich_text",
    "integer",
    "decimal",
    "date",
    "boolean",
    "enum",
    "asset",
    "relation",
    "json",
]
NullableTimestamp: TypeAlias = str | datetime | None
RecordData: TypeAlias = dict[str, Any]
WebhookEventType: TypeAlias = Literal[
    "record.created",
    "record.updated",
    "record.deleted",
    "record.published",
    "record.unpublished",
    "asset.created",
    "asset.deleted",
    "schema.changed",
]
