"""Generates the SDK's contract-derived code from openapi.json.

- src/nohead/models.py: Pydantic models of the API's schemas, for responses.
  They are lenient on purpose: unknown fields are kept and enums are plain
  strings, because the API adds fields and enum values without notice.
- src/nohead/params.py: TypedDicts of the request bodies, for type checkers.
  Enums are Literals here: what the SDK sends should be checked.
- src/nohead/_generated/operations.py: the method and path of every
  operation an API key can call.

Run with `uv run python scripts/generate.py` after updating openapi.json.
"""

from __future__ import annotations

import json
import keyword
import re
import subprocess
import textwrap
from pathlib import Path
from typing import Any

from pydantic import BaseModel

ROOT = Path(__file__).resolve().parent.parent
SPEC: dict[str, Any] = json.loads((ROOT / "openapi.json").read_text())
SCHEMAS: dict[str, Any] = SPEC["components"]["schemas"]
METHODS = ("get", "post", "put", "patch", "delete")
HEADER = "# Generated by scripts/generate.py from openapi.json. Do not edit.\n"

Schema = dict[str, Any]


def ref_name(schema: Schema) -> str | None:
    ref = schema.get("$ref")
    return ref.rsplit("/", 1)[1] if isinstance(ref, str) else None


def pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[_\W]+", name) if part)


def is_class(schema: Schema) -> bool:
    return "properties" in schema or "allOf" in schema


def docstring(text: str | None, indent: str) -> list[str]:
    if not text:
        return []
    text = text.strip().replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    lines = textwrap.wrap(" ".join(text.split()), 92 - len(indent))
    if len(lines) == 1:
        return [f'{indent}"""{lines[0]}"""']
    return [f'{indent}"""{lines[0]}', *(f"{indent}{line}" for line in lines[1:]), f'{indent}"""']


class Generator:
    """Writes one module of classes and aliases from the component schemas."""

    def __init__(self, mode: str, names: set[str]) -> None:
        self.mode = mode  # "model" or "params"
        self.names = names
        self.classes: list[list[str]] = []
        self.class_names: list[str] = []
        self.aliases: dict[str, tuple[str, set[str]]] = {}

    # Types ------------------------------------------------------------------

    def type_of(self, schema: Schema, parent: str) -> str:
        if name := ref_name(schema):
            return name
        for key in ("oneOf", "anyOf"):
            if key in schema:
                return self.union([self.type_of(s, parent) for s in schema[key]])
        if "allOf" in schema and len(schema["allOf"]) == 1:
            return self.type_of(schema["allOf"][0], parent)
        if "const" in schema:
            value = schema["const"]
            if self.mode == "params":
                return f"Literal[{json.dumps(value)}]"
            return {bool: "bool", int: "int", float: "float"}.get(type(value), "str")
        if "enum" in schema:
            values = [v for v in schema["enum"] if v is not None]
            nullable = None in schema["enum"]
            if self.mode == "params":
                base = f"Literal[{', '.join(json.dumps(v) for v in values)}]"
            else:
                base = "str" if all(isinstance(v, str) for v in values) else "Any"
            return f"{base} | None" if nullable else base
        kind = schema.get("type")
        if isinstance(kind, list):
            return self.union([self.type_of({**schema, "type": k}, parent) for k in kind])
        match kind:
            case "string":
                if schema.get("format") == "date-time":
                    return "str | datetime" if self.mode == "params" else "datetime"
                return "str"
            case "integer":
                return "int"
            case "number":
                return "float"
            case "boolean":
                return "bool"
            case "null":
                return "None"
            case "array":
                return f"list[{self.type_of(schema.get('items', {}), parent)}]"
            case "object" | None if "properties" in schema:
                return self.nested(schema, parent)
            case "object":
                extra = schema.get("additionalProperties")
                if isinstance(extra, dict) and extra:
                    return f"dict[str, {self.type_of(extra, parent)}]"
                return "dict[str, Any]"
            case _:
                return "Any"

    def union(self, types: list[str]) -> str:
        parts: list[str] = []
        for t in types:
            for part in t.split(" | "):
                if part not in parts:
                    parts.append(part)
        if "Any" in parts:
            return "Any"
        if "None" in parts:  # None last reads best
            parts = [p for p in parts if p != "None"] + ["None"]
        return " | ".join(parts)

    def nested(self, schema: Schema, parent: str) -> str:
        return self.add_class(parent, schema)

    # Declarations -----------------------------------------------------------

    def add_class(self, name: str, schema: Schema) -> str:
        if name in self.class_names:
            return name
        self.class_names.append(name)
        bases: list[str] = []
        props: dict[str, Schema] = {}
        required: set[str] = set()
        for part in schema.get("allOf", [schema]):
            if base := ref_name(part):
                bases.append(base)
            else:
                props.update(part.get("properties", {}))
                required.update(part.get("required", []))
        if "allOf" in schema:
            props.update(schema.get("properties", {}))
            required.update(schema.get("required", []))
        base_class = "NoheadModel" if self.mode == "model" else "TypedDict"
        lines = [f"class {name}({', '.join(bases) or base_class}):"]
        lines += docstring(schema.get("description"), "    ")
        for prop, prop_schema in props.items():
            lines += self.field(name, prop, prop_schema, prop in required)
        if len(lines) == 1 or (len(lines) == 2 and lines[1].strip().startswith('"""')):
            lines.append("    pass")
        self.classes.append(lines)
        return name

    def field(self, parent: str, prop: str, schema: Schema, required: bool) -> list[str]:
        annotation = self.type_of(schema, parent + pascal(prop))
        attribute = prop
        if self.mode == "model":
            clash = keyword.iskeyword(prop) or hasattr(BaseModel, prop) or not prop.isidentifier()
            if clash:
                attribute = re.sub(r"\W", "_", prop) + "_"
            default = ""
            if not required:
                annotation = self.union([annotation, "None"])
                default = " = None"
            if clash:
                default = f" = _Field({'None, ' if not required else ''}alias={json.dumps(prop)})"
            line = f"    {attribute}: {annotation}{default}"
        else:
            if keyword.iskeyword(prop) or not prop.isidentifier():
                raise SystemExit(f"{parent}.{prop}: a TypedDict key that is not an identifier")
            line = f"    {prop}: {annotation if required else f'NotRequired[{annotation}]'}"
        return [line, *docstring(schema.get("description"), "    ")]

    def add_schema(self, name: str) -> None:
        schema = SCHEMAS[name]
        if is_class(schema) and not (
            "allOf" in schema and len(schema["allOf"]) == 1 and ref_name(schema["allOf"][0])
        ):
            self.add_class(name, schema)
            return
        target = self.type_of(schema, name)
        self.aliases[name] = (target, set(re.findall(r"[A-Za-z_]\w*", target)))

    def render(self, imports: str) -> str:
        out = [HEADER, imports]
        for lines in self.classes:
            out.append("\n".join(lines) + "\n\n")
        # Aliases after the classes they name, and after the aliases they use.
        done: set[str] = set()
        pending = dict(self.aliases)
        while pending:
            for name, (target, uses) in list(pending.items()):
                if not (uses & set(pending)) - {name}:
                    out.append(f"{name}: TypeAlias = {target}\n")
                    done.add(name)
                    del pending[name]
        if self.mode == "model":
            out.append("\nfor _model in list(globals().values()):\n")
            out.append("    if isinstance(_model, type) and issubclass(_model, NoheadModel):\n")
            out.append("        _model.model_rebuild()\n")
        return "".join(out)


def schema_refs(schema: Any) -> set[str]:
    found: set[str] = set()
    if isinstance(schema, dict):
        if name := ref_name(schema):
            found.add(name)
        for value in schema.values():
            found |= schema_refs(value)
    elif isinstance(schema, list):
        for value in schema:
            found |= schema_refs(value)
    return found


def closure(names: set[str]) -> set[str]:
    todo, seen = list(names), set(names)
    while todo:
        for ref in schema_refs(SCHEMAS[todo.pop()]):
            if ref not in seen:
                seen.add(ref)
                todo.append(ref)
    return seen


def api_key_operations() -> list[tuple[str, str, str, Schema]]:
    found = []
    for path, item in SPEC["paths"].items():
        for method in METHODS:
            operation = item.get(method)
            if not operation:
                continue
            security = operation.get("security", SPEC["security"])
            if security and not any("apiKey" in s for s in security):
                continue
            found.append((operation["operationId"], method.upper(), path, operation))
    return sorted(found)


def main() -> None:
    operations = api_key_operations()

    # Models: every schema (responses can contain any of them).
    models = Generator("model", set(SCHEMAS))
    for name in SCHEMAS:
        models.add_schema(name)
    (ROOT / "src/nohead/models.py").write_text(
        models.render(
            '"""The API\'s resources, as the SDK returns them."""\n\n'
            "from __future__ import annotations\n\n"
            "from datetime import datetime\n"
            "from typing import Any, TypeAlias\n\n"
            "from pydantic import BaseModel as _BaseModel\n"
            "from pydantic import ConfigDict as _ConfigDict\n"
            "from pydantic import Field as _Field\n\n\n"
            "class NoheadModel(_BaseModel):\n"
            '    """Base of every model: fields the SDK does not know yet are kept."""\n\n'
            '    model_config = _ConfigDict(extra="allow", populate_by_name=True)\n\n\n'
        )
    )

    # Params: the request bodies of API-key operations and what they use.
    bodies: set[str] = set()
    for _, _, _, operation in operations:
        body = operation.get("requestBody", {}).get("content", {}).get("application/json", {})
        if name := ref_name(body.get("schema", {})):
            bodies.add(name)
    params = Generator("params", closure(bodies))
    for name in sorted(closure(bodies)):
        params.add_schema(name)
    (ROOT / "src/nohead/params.py").write_text(
        params.render(
            '"""The request bodies of the API, for type checkers."""\n\n'
            "from __future__ import annotations\n\n"
            "from datetime import datetime\n"
            "from typing import Any, Literal, NotRequired, TypeAlias, TypedDict\n\n\n"
        )
    )

    table = "".join(f'    "{op}": ("{method}", "{path}"),\n' for op, method, path, _ in operations)
    (ROOT / "src/nohead/_generated/operations.py").write_text(
        f'{HEADER}"""Every operation an API key can call: (method, path)."""\n\n'
        f"OPERATIONS: dict[str, tuple[str, str]] = {{\n{table}}}\n"
    )
    generated = ["src/nohead/models.py", "src/nohead/params.py", "src/nohead/_generated"]
    subprocess.run(["ruff", "format", "--quiet", *generated], cwd=ROOT, check=True)
    print(f"{len(operations)} operations, {len(SCHEMAS)} models, {len(params.class_names)} params")


if __name__ == "__main__":
    main()
