"""Generates the sync client (src/nohead/_sync) from the async one (src/nohead/_async).

The async code is the source: edit it, then run `uv run python scripts/unasync.py`.
Names starting with `Async` lose the prefix (AsyncRecords -> Records), `async` and
`await` go, and the names below are swapped for their sync counterparts.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "src/nohead/_async"
TARGET = ROOT / "src/nohead/_sync"

REPLACEMENTS = {
    "AsyncPaginator": "Page",
    "AsyncIterator": "Iterator",
    "AsyncIterable": "Iterable",
    "__aenter__": "__enter__",
    "__aexit__": "__exit__",
    "__aiter__": "__iter__",
    "__anext__": "__next__",
    "aclose": "close",
    "aread": "read",
    "aiter_file": "iter_file",
    "start_async_pages": "start_pages",
    "asyncio": "time",
}

HEADER = "# Generated by scripts/unasync.py from src/nohead/_async. Do not edit.\n"


def convert(source: str) -> str:
    text = re.sub(r"\bawait\s+", "", source)
    text = re.sub(r"\basync\s+(def|for|with)\b", r"\1", text)
    text = re.sub(r"\basync with\b", "with", text)

    def name(match: re.Match[str]) -> str:
        word = match.group(0)
        if word in REPLACEMENTS:
            return REPLACEMENTS[word]
        if word.startswith("Async") and word[5:6].isupper():
            return word[5:]
        return word

    text = re.sub(r"\b[A-Za-z_][A-Za-z0-9_]*\b", name, text)
    text = text.replace("An async client", "A client").replace("async client", "client")
    text = text.replace(" (async)", "")
    # AsyncPage and AsyncPaginator both become Page: import it once.
    return re.sub(r"(from \S+ import )\(?([^()\n]*(?:\n[^()]*)?)\)?", dedupe, text)


def dedupe(match: re.Match[str]) -> str:
    names = [n.strip() for n in match.group(2).replace("\n", " ").split(",") if n.strip()]
    unique = list(dict.fromkeys(names))
    if unique == names:
        return match.group(0)
    return f"{match.group(1)}{', '.join(unique)}"


def main() -> None:
    for path in sorted(SOURCE.rglob("*.py")):
        target = TARGET / path.relative_to(SOURCE)
        body = convert(path.read_text())
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text((HEADER + body) if body.strip() else "")
    subprocess.run(["ruff", "format", "--quiet", str(TARGET)], check=True)
    subprocess.run(["ruff", "check", "--fix", "--quiet", str(TARGET)], check=False)


if __name__ == "__main__":
    main()
