# Generated by scripts/unasync.py from src/nohead/_async. Do not edit.
from __future__ import annotations

from .._client import APIClient


class Resource:
    def __init__(self, client: APIClient) -> None:
        self._client = client
