# Generated by scripts/unasync.py from src/nohead/_async. Do not edit.
from __future__ import annotations

from typing import Literal

from typing_extensions import Unpack

from ..._errors import UploadError
from ..._pagination import Page
from ..._uploads import Uploadable, open_upload
from ...models import Asset, AssetUpload, DownloadUrl, ImageUrl
from ...params import AssetUploadCreate
from ._resource import Resource


class Assets(Resource):
    """Files of the key's project. `asset` is an asset ID (`ast_...`)."""

    def upload(
        self,
        file: Uploadable,
        *,
        filename: str | None = None,
        content_type: str | None = None,
        byte_size: int | None = None,
        idempotency_key: str | None = None,
    ) -> Asset:
        """Uploads a file and returns the `ready` asset: creates the upload, sends the
        bytes straight to storage, then completes it (which checks the file).

        `file` is bytes, a path, or a file opened in binary mode. Raises UploadError if
        storage refuses the bytes, and ValidationError if the file fails the checks.
        """
        source = open_upload(file, filename, content_type, byte_size)
        try:
            created = self.create_upload(
                filename=source.filename,
                content_type=source.content_type,
                byte_size=source.byte_size,
                idempotency_key=idempotency_key,
            )
            response = self._client.put_upload(
                created.upload.url, created.upload.method, created.upload.headers, source
            )
        finally:
            source.close()
        if not response.is_success:
            raise UploadError(
                f"Storage refused the upload of {source.filename} ({response.status_code})",
                response.status_code,
            )
        return self.complete(created.asset.id)

    def create_upload(
        self, *, idempotency_key: str | None = None, **params: Unpack[AssetUploadCreate]
    ) -> AssetUpload:
        """The first step of an upload: a `pending` asset and a presigned URL to PUT the
        bytes to (for example from a browser). Then `complete` it."""
        return self._client.request(
            "assets_upload", cast=AssetUpload, body=params, idempotency_key=idempotency_key
        )

    def complete(self, asset: str, *, idempotency_key: str | None = None) -> Asset:
        """Checks an uploaded file and marks the asset `ready`."""
        return self._client.request(
            "assets_complete",
            cast=Asset,
            path={"asset_id": asset},
            idempotency_key=idempotency_key,
        )

    def list(
        self, *, deleted: bool | None = None, limit: int | None = None, cursor: str | None = None
    ) -> Page[Asset]:
        return self._client.paginate(
            "assets_list",
            item=Asset,
            query={"deleted": deleted, "limit": limit, "cursor": cursor},
        )

    def get(self, asset: str) -> Asset:
        return self._client.request("assets_get", cast=Asset, path={"asset_id": asset})

    def delete(self, asset: str, *, idempotency_key: str | None = None) -> Asset:
        """Soft-deletes the asset; the file is purged after 30 days."""
        return self._client.request(
            "assets_delete",
            cast=Asset,
            path={"asset_id": asset},
            idempotency_key=idempotency_key,
        )

    def restore(self, asset: str, *, idempotency_key: str | None = None) -> Asset:
        return self._client.request(
            "assets_restore",
            cast=Asset,
            path={"asset_id": asset},
            idempotency_key=idempotency_key,
        )

    def image_url(
        self,
        asset: str,
        *,
        width: int | None = None,
        height: int | None = None,
        fit: Literal["contain", "cover", "fill"] | None = None,
        format: Literal["original", "webp", "avif", "jpeg", "png"] | None = None,
        quality: int | None = None,
    ) -> ImageUrl:
        """A signed, cacheable URL of an image rendition (`url`)."""
        return self._client.request(
            "assets_image_url",
            cast=ImageUrl,
            path={"asset_id": asset},
            query={
                "width": width,
                "height": height,
                "fit": fit,
                "format": format,
                "quality": quality,
            },
        )

    def download_url(self, asset: str) -> DownloadUrl:
        """A 15-minute link to download the original file (`url`)."""
        return self._client.request(
            "assets_download_url", cast=DownloadUrl, path={"asset_id": asset}
        )
