# Generated by scripts/unasync.py from src/nohead/_async. Do not edit.
from __future__ import annotations

from typing import Literal

from ..._pagination import Page
from ...models import AuditEvent, Principal
from ...models import FeatureFlags as FeatureFlagValues
from ...models import Health as HealthStatus
from ...types import RecordFilter
from ._resource import Resource


class AuditEvents(Resource):
    """The project's activity log, newest first. Needs the `audit:read` scope."""

    def list(
        self,
        *,
        filter: RecordFilter | None = None,
        sort: Literal["id", "-id"] | None = None,
        limit: int | None = None,
        cursor: str | None = None,
    ) -> Page[AuditEvent]:
        """`filter` takes `action` (exact, or a `record.*` prefix), `resource_type`,
        `resource_id`, `actor_type`, `actor_id`, `since` and `until`."""
        return self._client.paginate(
            "audit_events_list_for_project",
            item=AuditEvent,
            query={"filter": filter, "sort": sort, "limit": limit, "cursor": cursor},
        )


class FeatureFlags(Resource):
    def list(self) -> FeatureFlagValues:
        """Flags evaluated for the key's project."""
        return self._client.request("feature_flags_list", cast=FeatureFlagValues)


class Me(Resource):
    def get(self) -> Principal:
        """The API key: its project, scopes, `published_only` and expiry."""
        return self._client.request("me_get", cast=Principal)


class Health(Resource):
    def check(self) -> HealthStatus:
        return self._client.request("health_check", cast=HealthStatus)
