# Generated by scripts/unasync.py from src/nohead/_async. Do not edit.
from __future__ import annotations

from collections.abc import Mapping
from typing import Literal

from typing_extensions import Unpack

from ..._pagination import Page
from ...models import Webhook, WebhookDelivery, WebhookDeliveryDetail, WebhookWithSecret
from ...params import WebhookCreate, WebhookUpdate
from ...webhooks import WebhookEvent, unwrap
from .._client import APIClient
from ._resource import Resource


class Webhooks(Resource):
    """Webhooks of the key's project. `webhook` is a webhook ID (`wh_...`)."""

    def __init__(self, client: APIClient) -> None:
        super().__init__(client)
        self.deliveries = Deliveries(client)

    def list(self, *, limit: int | None = None, cursor: str | None = None) -> Page[Webhook]:
        return self._client.paginate(
            "webhooks_list", item=Webhook, query={"limit": limit, "cursor": cursor}
        )

    def get(self, webhook: str) -> Webhook:
        return self._client.request("webhooks_get", cast=Webhook, path={"webhook_id": webhook})

    def create(
        self, *, idempotency_key: str | None = None, **params: Unpack[WebhookCreate]
    ) -> WebhookWithSecret:
        """Subscribes a URL. The response is the only time `secret` is shown."""
        return self._client.request(
            "webhooks_create",
            cast=WebhookWithSecret,
            body=params,
            idempotency_key=idempotency_key,
        )

    def update(
        self, webhook: str, *, idempotency_key: str | None = None, **params: Unpack[WebhookUpdate]
    ) -> Webhook:
        return self._client.request(
            "webhooks_update",
            cast=Webhook,
            path={"webhook_id": webhook},
            body=params,
            idempotency_key=idempotency_key,
        )

    def delete(self, webhook: str, *, idempotency_key: str | None = None) -> Webhook:
        return self._client.request(
            "webhooks_delete",
            cast=Webhook,
            path={"webhook_id": webhook},
            idempotency_key=idempotency_key,
        )

    def rotate_secret(
        self, webhook: str, *, idempotency_key: str | None = None
    ) -> WebhookWithSecret:
        """A new signing secret; the old one stops working at once."""
        return self._client.request(
            "webhooks_rotate_secret",
            cast=WebhookWithSecret,
            path={"webhook_id": webhook},
            idempotency_key=idempotency_key,
        )

    def test(self, webhook: str, *, idempotency_key: str | None = None) -> WebhookDelivery:
        """Sends a `webhook.test` event to the URL."""
        return self._client.request(
            "webhooks_test",
            cast=WebhookDelivery,
            path={"webhook_id": webhook},
            idempotency_key=idempotency_key,
        )

    def unwrap(
        self,
        body: str | bytes,
        headers: Mapping[str, str],
        *,
        secret: str,
        tolerance: int = 300,
    ) -> WebhookEvent:
        """Checks a webhook request's signature and returns its event (see
        `nohead.webhooks.unwrap`, which needs no client)."""
        return unwrap(body, headers, secret=secret, tolerance=tolerance)


class Deliveries(Resource):
    """Delivery attempts of a webhook's events."""

    def list(
        self,
        webhook: str,
        *,
        status: Literal["pending", "succeeded", "failed"] | None = None,
        limit: int | None = None,
        cursor: str | None = None,
    ) -> Page[WebhookDelivery]:
        return self._client.paginate(
            "webhook_deliveries_list",
            item=WebhookDelivery,
            path={"webhook_id": webhook},
            query={"status": status, "limit": limit, "cursor": cursor},
        )

    def get(self, delivery: str) -> WebhookDeliveryDetail:
        return self._client.request(
            "webhook_deliveries_get", cast=WebhookDeliveryDetail, path={"delivery_id": delivery}
        )

    def retry(self, delivery: str, *, idempotency_key: str | None = None) -> WebhookDelivery:
        """Sends the event again."""
        return self._client.request(
            "webhook_deliveries_retry",
            cast=WebhookDelivery,
            path={"delivery_id": delivery},
            idempotency_key=idempotency_key,
        )
